/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bloodbank.Recipient;

import com.mycompany.bloodbank.HomePage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.time.LocalDate;

/**
 *
 * @author Swap
 */
public class RecipientAdd extends javax.swing.JFrame {

    /**
     * Creates new form Recipient
     */
    private Connection conn;
    
    public RecipientAdd() {
        initComponents();
        String dbURL = "jdbc:mysql://localhost:3306/bloodBankDB";
        String username = "root";
        String password = "abcd@1234";
            
        try {
                conn = DriverManager.getConnection(dbURL, username, password);
        }
        catch(Exception e)
        {
            System.out.println("Exception in recipient add");
        }
        addComboListValues();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        recName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        recAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        recQ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        recRegDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        recStaffID = new javax.swing.JComboBox<>();
        cityID = new javax.swing.JComboBox<>();
        managerID = new javax.swing.JComboBox<>();
        recBG = new javax.swing.JComboBox<>();
        recSex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recipient Form");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recipient Name");

        recName.setBackground(new java.awt.Color(0, 102, 102));
        recName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");

        recAge.setBackground(new java.awt.Color(0, 102, 102));
        recAge.setForeground(new java.awt.Color(255, 255, 255));
        recAge.setText(" ");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sex");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Blood Group");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Blood Quantity");

        recQ.setBackground(new java.awt.Color(0, 102, 102));
        recQ.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registration Date");

        recRegDate.setBackground(new java.awt.Color(0, 102, 102));
        recRegDate.setForeground(new java.awt.Color(255, 255, 255));
        recRegDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recRegDateActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Recording Staff ID");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City ID");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Manager ID");

        back.setForeground(new java.awt.Color(0, 102, 102));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        submit.setForeground(new java.awt.Color(0, 102, 102));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        recStaffID.setBackground(new java.awt.Color(0, 102, 102));
        recStaffID.setForeground(new java.awt.Color(255, 255, 255));

        cityID.setBackground(new java.awt.Color(0, 102, 102));
        cityID.setForeground(new java.awt.Color(255, 255, 255));

        managerID.setBackground(new java.awt.Color(0, 102, 102));
        managerID.setForeground(new java.awt.Color(255, 255, 255));

        recBG.setBackground(new java.awt.Color(0, 102, 102));
        recBG.setForeground(new java.awt.Color(255, 255, 255));
        recBG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "B+", "B-", "A+", "A-", "AB+", "AB-" }));

        recSex.setBackground(new java.awt.Color(0, 102, 102));
        recSex.setForeground(new java.awt.Color(255, 255, 255));
        recSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Others" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(recAge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(recName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(recSex, javax.swing.GroupLayout.Alignment.LEADING, 0, 86, Short.MAX_VALUE)
                                .addComponent(managerID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(recBG, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recStaffID, 0, 95, Short.MAX_VALUE)
                            .addComponent(cityID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recQ)
                            .addComponent(recRegDate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(submit)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(recName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(recAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(recQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(recRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(recSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(recBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(submit))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        addRecipient();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_submitActionPerformed

    private void recRegDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recRegDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recRegDateActionPerformed

    private void addComboListValues()
    {
//            String dbURL = "jdbc:mysql://localhost:3306/bloodBank";
//            String username = "root";
//            String password = "abcd@1234";
            
            try {
//                Connection conn = DriverManager.getConnection(dbURL, username, password);
 
                if (conn != null) {
                    System.out.println("Connected");
                } 
             
                String sql = "select * from recordingStaff";
                PreparedStatement st = conn.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                ResultSetMetaData res= rs.getMetaData();
                
                int col=res.getColumnCount(); 
                while(rs.next())
                {
                    StringBuilder c= new StringBuilder();
                    c.append(rs.getString("recordingStaffId")+" "); 
                    c.append(rs.getString("recordingStaffName"));
                    recStaffID.addItem(c.toString()); 
                }
//                this.add(BBManager);
                
                sql = "select * from city";
                st = conn.prepareStatement(sql);
                rs = st.executeQuery();
                res= rs.getMetaData();
                col=res.getColumnCount(); 
                while(rs.next())
                {
                    StringBuilder c= new StringBuilder();
                    c.append(rs.getString("cityId")+" "); 
                    c.append(rs.getString("cityName"));
                    cityID.addItem(c.toString()); 
                }
                
                sql = "select * from bloodBankManager";
                st = conn.prepareStatement(sql);
                rs = st.executeQuery();
                res= rs.getMetaData();
                col=res.getColumnCount(); 
                while(rs.next())
                {
                    StringBuilder c= new StringBuilder();
                    c.append(rs.getString("managerId")+" "); 
                    c.append(rs.getString("managerName"));
                    managerID.addItem(c.toString()); 
                }
                LocalDate timeObj= LocalDate.now();
                recRegDate.setText(timeObj.toString());                
                } 
             
            
            catch (Exception e) 
            {
                 System.out.println("Error in recipient add combo data");
            }
    }
    
    private void addRecipient()
    {
        String dbURL = "jdbc:mysql://localhost:3306/bloodBankDB";
            String username = "root";
            String password = "abcd@1234";
            
            try {
                Connection conn = DriverManager.getConnection(dbURL, username, password);
 
                if (conn != null) {
                    System.out.println("Connected");
                } 
                 
       
                String age =recAge.getText();
                String sex=(String) recSex.getSelectedItem();
                String name=recName.getText();
                String regDate=recRegDate.getText(); 
                String staffId= (String) recStaffID.getSelectedItem();
                staffId=staffId.substring(0,staffId.indexOf(" "));
                String manId= (String) managerID.getSelectedItem();
                manId=manId.substring(0,manId.indexOf(" "));
                String city= (String) cityID.getSelectedItem(); 
                city=city.substring(0,city.indexOf(" "));
                String bGrp= (String) recBG.getSelectedItem();
                String bQnty= recQ.getText();
                        
                String sql= "INSERT into recipient(recipientName,recipientAge,recipientBloodGroup,recipientQuantity,recordingStaffId,"+
                        "cityId,managerId,recipientSex,recipientRegistrationDate) VALUES(?,?,?,?,?,?,?,?,?)";
                PreparedStatement stmt = conn.prepareStatement(sql);
                
//                stmt.setString(1,recId);
                stmt.setString(1,name);
                stmt.setString(2,age);
                stmt.setString(3,bGrp);
                stmt.setString(4,bQnty);
                stmt.setString(5,staffId);
                stmt.setString(6,city);
                stmt.setString(7,manId);
                stmt.setString(8,sex);
                stmt.setString(9,regDate);
                stmt.executeUpdate(); 
                
                
                
//  recipientId int NOT NULL, recipientName varchar(1000) NOT NULL, recipientAge varchar(1000), recipientBloodGroup varchar(1000), 
//  recipientQuantity float, recordingStaffId int NOT NULL, 
//  cityId int NOT NULL, managerId int NOT NULL, recipientSex varchar(1000), recipientRegistrationDate date
                  
//                String sql= "INSERT INTO Recipient values (?, ?, ?, ?)";
//                PreparedStatement stmt = conn.prepareStatement(sql);
//                
//                stmt.setString(1,id);
//                  
//                stmt.executeUpdate(); 
                } 
            
            catch (Exception e) 
            {
                 System.out.println("Error in save new recipient");
                 e.printStackTrace();
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipientAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipientAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> cityID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> managerID;
    private javax.swing.JTextField recAge;
    private javax.swing.JComboBox<String> recBG;
    private javax.swing.JTextField recName;
    private javax.swing.JTextField recQ;
    private javax.swing.JTextField recRegDate;
    private javax.swing.JComboBox<String> recSex;
    private javax.swing.JComboBox<String> recStaffID;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
